image: python:2.7

before_script:
  - pip install -r requirements_test.txt

test:
    script:
        - pip install coverage
        - coverage run --source app -m pytest
        - coverage report
    coverage: '/TOTAL.+ ([0-9]{1,3}%)/'
