DEBUG = False
DATABASE = 'database.db'
DATABASE_KEY_FILE = 'database.key'
UPLOAD_FOLDER = 'uploads'
ALLOWED_EXTENSIONS = set(['.png', '.jpg', '.jpeg'])
MAX_CONTENT_LENGTH = 20 * 1024 * 1024
# 1 hour
MAX_CSRF_TOKEN_AGE = 3600
CSRF_METHODS = ['POST', 'PUT', 'DELETE']
MAX_SESSION_AGE_DAYS = 7
MAX_SESSION_AGE = MAX_SESSION_AGE_DAYS * 60 * 60 * 3600

RECAPTCHA_ENABLED = True
RECAPTCHA_PUBLIC_KEY = "XXXXXXXXXXXXXXXXXXXXX"
RECAPTCHA_SECRET_KEY = "XXXXXXXXXXXXXXXXXXXXX"
