DEBUG = False
DATABASE = 'database.db'
DATABASE_KEY_FILE = 'database.key'
DATABASE_ENCRYPT = True
UPLOAD_FOLDER = 'uploads'
IMAGE_EXTENSIONS = set(['.png', '.jpg', '.jpeg'])
MAX_CONTENT_LENGTH = 20 * 1024 * 1024
# 1 hour
MAX_CSRF_TOKEN_AGE = 3600
CSRF_METHODS = ['POST', 'PUT', 'DELETE']
# 7 days
MAX_SESSION_AGE = 7 * 60 * 60 * 24
# Recaptcha keys for Google Recaptcha
RECAPTCHA_ENABLED = not DEBUG
RECAPTCHA_PUBLIC_KEY = "XXXXXXXXXXXXXXXXXXXXX"
RECAPTCHA_SECRET_KEY = "XXXXXXXXXXXXXXXXXXXXX"
# CSP reporting URL on Sentry
CSP_REPORT_URI = "https://sentry.io/api/252244/csp-report/?sentry_key=XXXXXXXXXXXXXXXXXXXXX"
# Email settings
MAIL_SERVER = 'smtp.gmail.com'
MAIL_PORT = 587
MAIL_USE_TLS = True
MAIL_USE_SSL = False
MAIL_USERNAME = 'XXXXXXXXXXXXXXXXXXXXX'
MAIL_PASSWORD = 'XXXXXXXXXXXXXXXXXXXXX'
# 1 hour password recovery timeout
PASSWORD_RECOVERY_EXPIRATION_TIMEOUT = 1 * 60 * 60

