BEGIN TRANSACTION;
CREATE TABLE "Users" (
	`id`	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
	`username`	TEXT NOT NULL UNIQUE,
	`password_salt`	TEXT NOT NULL,
	`password_token`	TEXT NOT NULL,
	`is_admin`	INTEGER NOT NULL
);
CREATE TABLE `Sessions` (
	`id`	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
	`user_id`	INTEGER NOT NULL,
	`session_token`	TEXT NOT NULL UNIQUE
);
CREATE TABLE `Posts` (
	`id`	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
	`author_id`	INTEGER NOT NULL,
	`content`	TEXT
);
CREATE TABLE `Messages` (
	`id`	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
	`author_id`	INTEGER NOT NULL,
	`recipient_id`	INTEGER NOT NULL,
	`content`	TEXT,
	`filename`	TEXT
);
COMMIT;
